Erikyvanov/subcommets reply
migala-dev/demos-app pull request #172
Opened 2022-08-09 07:25 UTC by erikyvanov

2022-08-16 17:21 UTC, AlexOrtegaZ requested changes

2022-08-16 17:21 UTC, AlexOrtegaZ commented on lib/modules/proposals/pages/proposal_comments/cubit/comment_reply_state.dart
> +  factory CommentReplyState.empy() => const CommentReplyState(null);
CommentReplyState.empy
Creo que empty aqui

2022-08-16 17:21 UTC, AlexOrtegaZ commented on lib/modules/proposals/pages/proposal_comments/widgets/mention_tile.widget.dart
> +      width: width + 0.0,
Tiene alguna función el 0.0? Si no la tiene hay que eliminar el código.

2022-08-16 17:21 UTC, AlexOrtegaZ commented on lib/modules/proposals/pages/proposal_comments/services/comment_mention_preprocessor.service.dart
> +    final commentParts = split(comment).where((part) => !part.isMention);
"split" no es una nombnre de función descriptivo "splitCommentByMentions"

2022-08-16 17:21 UTC, AlexOrtegaZ commented on lib/modules/proposals/pages/proposal_comments/services/comment_mention_preprocessor.service.dart
> +    if (!isUUID(uuid)) {
En este caso uuid se refiere al memeberId únicamente?

2022-08-16 17:21 UTC, AlexOrtegaZ commented on lib/modules/proposals/pages/proposal_comments/widgets/input_comment.widget.dart
> +    final addMention = commentReplyCubit.state.addMention;
Podemos renombrar "addMention" por "isReplyingASubComment" ?
Recuerda que es un poco confuso cuando empiezas la primera palabra de la variable con un verbo

2022-08-16 17:21 UTC, AlexOrtegaZ commented on lib/modules/proposals/pages/proposal_comments/widgets/input_comment.widget.dart
> +        ? CommentMentionPreprocessorService.addMentionToStart(
Igual aqui "addMentionToStart" me parece un poco confuso, lo que hace es concatenar la mención al inicio del contenido del mensaje (supongo que por eso la nombraste así, aunque en ese caso que seria mejor la palabra AtBegining) pero yo le pondría "appendMentionAtBeginigOfTheMessage"

2022-08-22 06:38 UTC, erikyvanov commented on lib/modules/proposals/pages/proposal_comments/cubit/comment_reply_state.dart
> +  factory CommentReplyState.empy() => const CommentReplyState(null);
No entiendo

2022-08-22 06:51 UTC, erikyvanov commented on lib/modules/proposals/pages/proposal_comments/cubit/comment_reply_state.dart
> +  factory CommentReplyState.empy() => const CommentReplyState(null);
Aaaa ya
Es verdad

2022-10-25 01:17 UTC, AlexOrtegaZ approved these changes

2022-10-25 01:17 UTC, merged